services:
  - type: web
    name: yesgo-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_URL
        fromDatabase:
          name: yesgo-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: APP_URL
        sync: false
      - key: CINETPAY_API_KEY
        sync: false
      - key: CINETPAY_SITE_ID
        sync: false
      - key: CINETPAY_TRANSFER_PASSWORD
        sync: false
      - key: YESGO_COMMISSION_PERCENT
        value: "10"
      - key: BETA_MODE
        value: "false"
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false

databases:
  - name: yesgo-db
    databaseName: yesgo
    plan: free
